title: Mapa Pomocy
description: Bezpłatny przewodnik po systemie wsparcia społecznego w Polsce.
url: https://mapapomocy.pl
baseurl: ""
lang: pl
author: Igor Pabiańczyk

# Wyklucz pliki, które nie powinny trafić na stronę
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
